### ISSUE TITLE
No module named oslo.transformers.data when running mBart test.

### ISSUE THREAD

**Issue by josemlopez** [EleutherAI/oslo#13]
## How to reproduce

```python
python ./tests/transformers/models/mbart/test_training.py
```

## Environment

- OS : CentOS 7.9
- Python version : 3.9
- Transformers version : 4.21.2
- Whether to use Docker:
- Misc.:

```
# python ./tests/transformers/models/mbart/test_training.py
 
Traceback (most recent call last):
  File "./tests/transformers/models/mbart/test_training.py", line 2, in <module>
    from oslo.transformers.trainer import Trainer as OTrainer
  File "/opt/conda/lib/python3.7/site-packages/oslo_core-3.0.0-py3.7.egg/oslo/transformers/trainer.py", line 37, in <module>
    from .data.data_collator import (
ModuleNotFoundError: No module named 'oslo.transformers.data'

```

I've changed included `__init__.py` in the oslo/transformers/data folder to continue with the tests.

**Comment by hyunwoongko** [comment]
Fixed by https://github.com/EleutherAI/oslo/pull/16
